#!/bin/sh

# script/init: Initializes a new project

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Initializing Symfony 2 application…"
if [ ! -d api/src ]; then
  docker run \
    --rm \
    --volume "$(pwd)":/app \
    --entrypoint /usr/local/bin/entrypoint-suexec.sh
    dreadlabs/php-symfony:7.3-dev \
    symfony --no-ansi new api 3.4
else
  echo "==> Symfony 2 application already initialized"
fi

echo "==> Project initialized."
